require('dotenv').config();

function mapPresence(val) {
    const mapping = {
        typing: 'composing',
        online: 'available',
        recording: 'recording',
        paused: 'paused',
        offline: 'unavailable'
    };
    return mapping[val?.toLowerCase()?.trim()] || 'paused';
}

module.exports = {
    prefixes: process.env.PREFIX
        ? process.env.PREFIX.split(',').map(p => p.trim())
        : [''],

    NUMBER: process.env.YOUR_NUMBER || '2347072050737',
    MODE: (process.env.MODE || 'private').toLowerCase().trim(),
    WARN_LIMIT: process.env.WARNINGS || '3',
    ON: process.env.YOUR_NAME || 'FLASH-MD',
    ANTICALL: process.env.ANTICALL || 'on',
    ADM: process.env.ANTIDELETE || 'on',
    AR: process.env.AUTO_REACTION || 'off',

    AUTO_VIEW_STATUS: process.env.AUTO_READ_STATUS === 'on',
    AUTO_LIKE: process.env.AUTO_LIKE === 'on',
    AUTO_READ_MESSAGES: process.env.AUTO_READ_DM === 'on',
    HEROKU_API_KEY: process.env.HEROKU_API_KEY,
    HEROKU_APP_NAME: process.env.HEROKU_APP_NAME,
    sessionBase64: process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoic0tQek9hM2dPbjNMcndScHppbVU3bWxhTkxpUjF1UnFuNERHYTN0WFEwZz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiK21hTGR3V1YvQmpQcjJCb3pRZ3lTancySldvVjNlQUJZa1EvUjFqazNoWT0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJnSFJvcit4aWhTMmpseHR6WitQZ2hLZndZNStuQk9CLzFTa0F6aFpaNGtzPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiI4dnhaaENtc1VhT2JqK243WVpjc2lIVE1WOG05NTRkT2QveFhrVVI4c0hRPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkdNeUJYSURnNWp3djJaYzdoT3VrT1Rla09VTjl2SkIybms0WS9QVTJxMDg9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlM3TXZmbkRGV1BjMlJVMXhqM296WnF3SkNYc1lMdXRlb2dOT0ZXVytua1k9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiNkExdGIwcWlIeVhnanVwR1JNZG93MXUrb0JEdllHcDVBNC9WZ2dOdGdrUT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiVW1hMU1rc3VCU2ZCWURoL201M2hLRElXVXZkSDZVSHIzNTJFZEgvZU1Rcz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImwzS2t5ZUppTkMzTVVKR2tSdzNIN0hHTHEwcnFwMjNNd2xHYzlZN0Jkc0YrMSttVWdZM0RUNm0vM2tEcXhDc3JSRTVNMnhpTmIxWHdYWVcwUjFHK2pRPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTc2LCJhZHZTZWNyZXRLZXkiOiJ0UmQ2Wmw2QXRlYkRmUlpjeVlERC9QM2FJaXlyQ0xtYTNxZUZnaUxLVXhVPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W3sia2V5Ijp7InJlbW90ZUppZCI6IjIzNDcwNzIwNTA3MzdAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiM0E3MTlGMTY2QjFBMURENkZCQjYifSwibWVzc2FnZVRpbWVzdGFtcCI6MTc1Mzk4NDEzM30seyJrZXkiOnsicmVtb3RlSmlkIjoiMjM0NzA3MjA1MDczN0BzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiIzQTUzMDBEOTM5QjYwOEIwQ0MxOCJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzUzOTg0MTM2fSx7ImtleSI6eyJyZW1vdGVKaWQiOiIyMzQ3MDcyMDUwNzM3QHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6IjNBQzVFOTZCRkJCODgzMDdDQTJBIn0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3NTM5ODQxNTR9LHsia2V5Ijp7InJlbW90ZUppZCI6IjIzNDcwNzIwNTA3MzdAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiM0ExMUZCRTJFOEU0NEFDMzNBNzQifSwibWVzc2FnZVRpbWVzdGFtcCI6MTc1Mzk4NDE3NH1dLCJuZXh0UHJlS2V5SWQiOjMxLCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZCI6MzEsImFjY291bnRTeW5jQ291bnRlciI6MSwiYWNjb3VudFNldHRpbmdzIjp7InVuYXJjaGl2ZUNoYXRzIjpmYWxzZX0sInJlZ2lzdGVyZWQiOnRydWUsInBhaXJpbmdDb2RlIjoiRlIxVlYzUUUiLCJtZSI6eyJpZCI6IjIzNDcwNzIwNTA3Mzc6NDVAcy53aGF0c2FwcC5uZXQiLCJsaWQiOiIxMjEyMjE3Mjc0MjA2NjA6NDVAbGlkIiwibmFtZSI6IkFrYXRzdWtpIFNob3AifSwiYWNjb3VudCI6eyJkZXRhaWxzIjoiQ0x2ZjhJZ05FTy9ZcnNRR0dBRWdBQ2dBIiwiYWNjb3VudFNpZ25hdHVyZUtleSI6InZ5eWpzS2pZc2ZnUXhmRStNZURYYmdPK1FBa0hucXhhbHQ5dmVza1FzQ2c9IiwiYWNjb3VudFNpZ25hdHVyZSI6Ill0dXlZTDlFdUxYai8zU1V1OFc2NTNVZ1k4M1NPRHdjVUxPOGxpUUFJQXc3bTRRU1lhaTd6a3ZDekZnemYyeWZURm81RFUzVUs2bXExbC9iVXVlTmh3PT0iLCJkZXZpY2VTaWduYXR1cmUiOiJYNFJKVU5IZkJPR2FFenBiNXpVNzI4OURPNEdQNGJnZG1wNEhhaEhheCtOOFVhQi8vTEtmaWxWL2JoNFRMT3dnZ1V2L0hiM1piVmxWRFZhRVVhbUtqUT09In0sInNpZ25hbElkZW50aXRpZXMiOlt7ImlkZW50aWZpZXIiOnsibmFtZSI6IjIzNDcwNzIwNTA3Mzc6NDVAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCYjhzbzdDbzJMSDRFTVh4UGpIZzEyNER2a0FKQjU2c1dwYmZiM3JKRUxBbyJ9fV0sInBsYXRmb3JtIjoiaXBob25lIiwicm91dGluZ0luZm8iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJDQVVJRFE9PSJ9LCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3NTM5ODQxMjQsImxhc3RQcm9wSGFzaCI6IjJHNEFtdSIsIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBUDBiIn0=',
    timezone: 'Africa/Nairobi',

    USER_LID: process.env.YOUR_LID, 

    PRESENCE_DM: mapPresence(process.env.PRESENCE_DM || 'typing'),
    PRESENCE_GROUP: mapPresence(process.env.PRESENCE_GROUP || 'recording'),

    mapPresence
};
